### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by ghost** [RX64d/Debloat-without-linux-PC-Tuning#1]
I don't mind testing and reporting back with the results if you add all the features from the current bash script. Currently, it is missing [these exclusions](https://github.com/amitxv/PC-Tuning/blob/fcde9ce0cad25e2ea8000cf97803904739a304a3/win-debloat.sh#L16C1-L19).

**Comment by RX64d** [comment]
https://github.com/RX64d/Debloat-without-linux-PC-Tuning/releases/tag/v0.0.2

**Comment by ghost** [comment]
This is still missing [these exclusions](https://github.com/amitxv/PC-Tuning/blob/fcde9ce0cad25e2ea8000cf97803904739a304a3/win-debloat.sh#L16C1-L19).
